### ISSUE TITLE
Update the lesson

### ISSUE THREAD

**Issue by seyma-tas** [learn-co-curriculum/dsc-spark-docker-installation#2]
docker and kitematic part of this lesson should be updated, new docker doesn't have kitematic

**Comment by lindseyberlin** [comment]
Steps to fix this lesson:

- Students should still be able to download Docker through the install links currently provided
- Need to remove all mention of Kitematic - that's now integrated through Docker Dashboard it looks like
- Once students have installed Docker Desktop and created a Docker Hub account, they can test their install with `docker run hello-world`
- To get the jupyter pyspark image, they'll pull from https://hub.docker.com/r/jupyter/pyspark-notebook (or they can search `docker search pyspark` in their terminal to see the jupyter/pyspark-notebook image) - terminal command is `docker pull jupyter/pyspark-notebook`(note: they might not need to pull separately? I believe the command `docker run` will pull if it doesn't find the image locally)
- To run the jupyter pyspark image, run `docker run -p 8888:8888 jupyter/pyspark-notebook` (the `-p 8888:8888` makes sure it runs on host port 8888 for simplicity's sake, so instructors can help students more easily)
- For me, the jupyter browser window did not open automatically - if that happens, students should copy/paste the link starting with `http://127.0.0.1:8888/?token=` into a browser (they need to make sure they copy/paste the full link, including their token) 
- From there, they should see a `work` folder - students should navigate into there, create a new jupyter notebook, and run the command at the bottom

Just a note - this should not be an IllumiDesk code_lesson on Canvas, but should be a page (all needs to be run locally, won't/shouldn't run in IllumiDesk)
Another note - this worked for me, running the most recent version of Catalina on a Mac. I believe it should be about the same for anyone running Windows 10 Pro, but the instructions might be different for anyone using Windows 7 or Windows 10 Home (might have to use Docker Toolbox + Kitematic ...?)

**Comment by hoffm386** [comment]
Updated in latest version
